// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdbtuwixjrhoozofnmdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkYnR1d2l4anJob296b2ZubWRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTQ2NTIsImV4cCI6MjA3MzkzMDY1Mn0.UzceV4a11oyEwh0IGQJalLxMTyecH1KEPiZDYa2mW40";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});